[package]
name = "afterglow"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
pgwire = "0.40"
async-trait = "0.1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "std",
    "registry",
    "env-filter",
    "fmt",
] }
futures = "0.3"
tokio-postgres = "0.7.17"
deadpool-postgres = "0.14.1"
pg_query = "6.1.1"
regex = "1.12.4"
base64 = "0.22.1"
prometheus = "0.14.0"
axum = "0.8.9"
uuid = { version = "1.26.0", features = ["std", "v7"] }
reqwest = "0.13.4"

[[bin]]
name = "afterglow"
path = "src/main.rs"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "warn"
panic = "warn"
